# Copyright 2024 Google.
# This software is provided as-is, without warranty or representation for any use or purpose.
# Your use of it is subject to your agreement with Google.
steps:
- id: fetch-repository
  name: 'europe-west2-docker.pkg.dev/oms-maas/containers/pipe-builder'
  env:
  - 'REPO_NAME=$REPO_NAME'
  - 'SHORT_SHA=$SHORT_SHA'
  automapSubstitutions: true
  script: |
    #!/bin/bash
    echo "-------------------"
    echo "COMMIT_SHA: ${COMMIT_SHA}"
    echo "-------------------"
    echo "--> git fetch:"
    git fetch --depth=2
    echo "-------------------"
- id: set-environment
  name: 'europe-west2-docker.pkg.dev/oms-maas/containers/pipe-builder'
  script: |
    #!/bin/bash
    echo "-------------------"
    echo "--> git show:"
    git show --name-only --oneline $COMMIT_SHA
    echo "-------------------"
    export PIPELINE=$(git show --name-only --oneline | head -n 2 | tail -n 1 | cut -d '/' -f 1)
    echo "PIPELINE: ${PIPELINE}"
    echo ${PIPELINE} > /workspace/env_pipeline.txt
    echo "-------------------"
    cd $PIPELINE
    ls -la pipeline.py
    echo "-------------------"
    export PACKAGE=$(grep dsl.pipeline pipeline.py | sed "s/.*name='\(.*\)',.*/\1/")
    echo "PACKAGE: ${PACKAGE}"
    echo ${PACKAGE} > /workspace/env_package.txt
    echo "-------------------"
    export PIPELINE_FUNCTION=$(sed -n '/^@dsl.pipeline/{n;p;}' pipeline.py)
    echo "PIPELINE_FUNCTION: ${PIPELINE_FUNCTION}"
    echo ${PIPELINE_FUNCTION} > /workspace/env_pipeline_function.txt
    echo "-------------------"
    export SIGNATURE=$(echo $PIPELINE_FUNCTION | sed 's/.*(\(.*\)).*/\1/')
    echo "SIGNATURE: ${SIGNATURE}"
    echo ${SIGNATURE} > /workspace/env_signature.txt
    echo "-------------------"
- id: confirm-container-location
  name: 'europe-west2-docker.pkg.dev/oms-maas/containers/pipe-builder'
  script: |
    #!/bin/bash
    echo "-------------------"
    echo "run container location test"
    export PIPELINE=$(cat /workspace/env_pipeline.txt)
    cd /workspace/${PIPELINE}
    echo "-------------------"
- id: upload-pipeline
  name: 'europe-west2-docker.pkg.dev/oms-maas/containers/pipe-builder'
  env:
  - 'REPO_NAME=$REPO_NAME'
  - 'SHORT_SHA=$SHORT_SHA'
  automapSubstitutions: true
  script: |
    #!/bin/bash
    echo "-------------------"
    echo "Setting env variables..."
    export PACKAGE=$(cat /workspace/env_package.txt)
    export PIPELINE=$(cat /workspace/env_pipeline.txt)
    export PIPELINE_FUNCTION=$(cat /workspace/env_pipeline_function.txt)
    export SIGNATURE=$(cat /workspace/env_signature.txt)
    source /env/bin/activate
    echo "-------------------"
    cd /workspace/${PIPELINE}
    echo "Compiling pipeline..."
    python3 pipeline.py
    echo "-------------------"
    echo "Going to upload pipeline..."
    python3 /workspace/scripts/upload-pipeline.py
    if [ $? -ne 0 ]; then
      exit 1
    fi
    echo "-------------------"
substitutions:
  _REGION: europe-west2
options:
  logging: CLOUD_LOGGING_ONLY
