# Copyright 2024 Google.
# This software is provided as-is, without warranty or representation for any use or purpose.
# Your use of it is subject to your agreement with Google.
#
# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml
steps:
- id: main-push-build
  name: 'europe-west2-docker.pkg.dev/oms-maas/containers/pipe-builder'
  env:
  - 'REPO_NAME=$REPO_NAME'
  - 'SHORT_SHA=$SHORT_SHA'
  automapSubstitutions: true
  script: |
    #!/bin/bash
    echo "-------------------"
    echo "hello from pr-main"
    echo "-------------------"
    source /env/bin/activate
    echo "-------------------"
    echo "pwd: $(pwd)"
    echo "-------------------"
    git status
    echo "-------------------"
    echo "COMMIT_SHA: ${COMMIT_SHA}"
    echo "-------------------"
    echo "--> git fetch:"
    git fetch --depth=3
    echo "-------------------"
    echo "--> git show:"
    git show --name-only --oneline $COMMIT_SHA
    echo "-------------------"
substitutions:
  _REGION: europe-west2
options:
  logging: CLOUD_LOGGING_ONLY
