# Copyright 2024 Google.
# This software is provided as-is, without warranty or representation for any use or purpose.
# Your use of it is subject to your agreement with Google.
#
# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml
steps:
- name: 'gcr.io/google.com/cloudsdktool/google-cloud-cli:slim'
  env:
  - 'REPO_NAME=$REPO_NAME'
  - 'SHORT_SHA=$SHORT_SHA'
  automapSubstitutions: true
  script: |
    #!/bin/bash
    echo "-------------------"
    echo "hello from pr-main"
    echo "-------------------"
    apt install -y python3.11-venv && \
    python3 -m venv env && \
    source env/bin/activate && \
    pip3 install google-cloud-aiplatform && \
    pip3 install kfp && \
    pip3 install sha256sum
    echo "-------------------"
    echo "pwd: $(pwd)"
    echo "-------------------"
    ls -la
    echo "-------------------"
    git status
    echo "COMMIT_SHA: ${COMMIT_SHA}"
    echo "-------------------"
    echo "--> git fetch:"
    git fetch --depth=2
    echo "-------------------"
    echo "--> git show:"
    git show --name-only --oneline $COMMIT_SHA
    export PIPELINE=$(git show --name-only --oneline | head -n 2 | tail -n 1 | cut -d '/' -f 1)
    echo "-------------------"
    echo "PIPELINE: ${PIPELINE}"
    echo "-------------------"
    cd $PIPELINE
    ls -la pipeline.py
    echo "-------------------"
    sed -n '/^@dsl.pipeline/{n;p;}' pipeline.py
    echo "-------------------"
substitutions:
  _REGION: europe-west2
options:
  logging: CLOUD_LOGGING_ONLY
