# Copyright 2024 Google.
# This software is provided as-is, without warranty or representation for any use or purpose.
# Your use of it is subject to your agreement with Google.
steps:
- id: test-pipeline
  name: 'europe-west2-docker.pkg.dev/oms-maas/containers/pipe-builder'
  env:
  - 'REPO_NAME=$REPO_NAME'
  - 'SHORT_SHA=$SHORT_SHA'
  automapSubstitutions: true
  script: |
    #!/bin/bash
    echo "test pipeline"
- id: set-environment
  name: 'europe-west2-docker.pkg.dev/oms-maas/containers/pipe-builder'
  script: |
    #!/bin/bash
    echo "-------------------"
    echo "--> git show:"
    git show --name-only --oneline $COMMIT_SHA
    echo "-------------------"
    export PIPELINE=$(git show --name-only --oneline | head -n 2 | tail -n 1 | cut -d '/' -f 1)
    echo "PIPELINE: ${PIPELINE}"
    echo ${PIPELINE} > /workspace/env_pipeline.txt
    echo "-------------------"
    cd $PIPELINE
    ls -la pipeline.py
    echo "-------------------"
    export PACKAGE=$(grep dsl.pipeline pipeline.py | sed "s/.*name='\(.*\)',.*/\1/")
    echo "PACKAGE: ${PACKAGE}"
    echo ${PACKAGE} > /workspace/env_package.txt
    echo "-------------------"
- id: create-deploy
  name: 'europe-west2-docker.pkg.dev/oms-maas/containers/pipe-builder'
  env:
  - 'REPO_NAME=$REPO_NAME'
  - 'SHORT_SHA=$SHORT_SHA'
  automapSubstitutions: true
  script: |
    #!/bin/bash
    echo "create deploy"
substitutions:
  _REGION: europe-west2
options:
  logging: CLOUD_LOGGING_ONLY
