# Copyright 2024 Google.
# This software is provided as-is, without warranty or representation for any use or purpose.
# Your use of it is subject to your agreement with Google.
steps:
- id: test-pipeline
  name: 'europe-west2-docker.pkg.dev/oms-maas/containers/pipe-builder'
  env:
  - 'REPO_NAME=$REPO_NAME'
  - 'SHORT_SHA=$SHORT_SHA'
  automapSubstitutions: true
  script: |
    #!/bin/bash
    echo "test pipeline"
- id: create-deploy
  name: 'europe-west2-docker.pkg.dev/oms-maas/containers/pipe-builder'
  env:
  - 'REPO_NAME=$REPO_NAME'
  - 'SHORT_SHA=$SHORT_SHA'
  automapSubstitutions: true
  script: |
    #!/bin/bash
    echo "create deploy"
substitutions:
  _REGION: europe-west2
options:
  logging: CLOUD_LOGGING_ONLY
